include(Findosg_functions)
OSG_FIND_PATH   (OSGQOPENGL osgQOpenGL/Export)
OSG_FIND_LIBRARY(OSGQOPENGL osgQOpenGL)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(osgQOpenGL DEFAULT_MSG
  OSGQOPENGL_LIBRARY OSGQOPENGL_INCLUDE_DIR)